# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lastgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedwidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedwidget.setGeometry(QtCore.QRect(0, 0, 501, 701))
        self.stackedwidget.setObjectName("stackedwidget")
        self.join_server_page = QtWidgets.QWidget()
        self.join_server_page.setObjectName("join_server_page")
        self.ip_page = QtWidgets.QFrame(self.join_server_page)
        self.ip_page.setGeometry(QtCore.QRect(0, 0, 501, 701))
        self.ip_page.setStyleSheet("QFrame#ip_page{\n"
"background-color: rgb(179, 179, 179);\n"
"}")
        self.ip_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ip_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ip_page.setObjectName("ip_page")
        self.ip_text_frame = QtWidgets.QFrame(self.ip_page)
        self.ip_text_frame.setGeometry(QtCore.QRect(50, 330, 411, 81))
        self.ip_text_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.ip_text_frame.setStyleSheet("QFrame#ip_text_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.ip_text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ip_text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ip_text_frame.setObjectName("ip_text_frame")
        self.ip_text_box = QtWidgets.QLineEdit(self.ip_text_frame)
        self.ip_text_box.setGeometry(QtCore.QRect(10, 20, 391, 41))
        self.ip_text_box.setStyleSheet("QLineEdit#ip_text_box{\n"
"border-radius: 12px;\n"
"padding-left: 4px;\n"
"}")
        self.ip_text_box.setText("")
        self.ip_text_box.setObjectName("ip_text_box")
        self.ip_frame = QtWidgets.QFrame(self.ip_page)
        self.ip_frame.setGeometry(QtCore.QRect(60, 180, 391, 61))
        self.ip_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.ip_frame.setStyleSheet("QFrame#ip_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.ip_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ip_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ip_frame.setObjectName("ip_frame")
        self.ip_label = QtWidgets.QLabel(self.ip_frame)
        self.ip_label.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.ip_label.setStyleSheet("QLabel#ip_label{\n"
"border-radius: 10px;\n"
"}")
        self.ip_label.setObjectName("ip_label")
        self.signup_frame = QtWidgets.QFrame(self.ip_page)
        self.signup_frame.setGeometry(QtCore.QRect(50, 470, 181, 81))
        self.signup_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.signup_frame.setStyleSheet("QFrame#signup_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.signup_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signup_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signup_frame.setObjectName("signup_frame")
        self.signup_btn = QtWidgets.QPushButton(self.signup_frame)
        self.signup_btn.setGeometry(QtCore.QRect(20, 20, 141, 41))
        self.signup_btn.setStyleSheet("QPushButton#signup_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.signup_btn.setObjectName("signup_btn")
        self.login_frame = QtWidgets.QFrame(self.ip_page)
        self.login_frame.setGeometry(QtCore.QRect(270, 470, 181, 81))
        self.login_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.login_frame.setStyleSheet("QFrame#login_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.login_btn = QtWidgets.QPushButton(self.login_frame)
        self.login_btn.setGeometry(QtCore.QRect(20, 20, 141, 41))
        self.login_btn.setStyleSheet("QPushButton#login_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.stackedwidget.addWidget(self.join_server_page)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.username_page_frame_2 = QtWidgets.QFrame(self.login_page)
        self.username_page_frame_2.setGeometry(QtCore.QRect(0, 0, 501, 701))
        self.username_page_frame_2.setStyleSheet("QFrame#username_page_frame{\n"
"background-color: rgb(179, 179, 179);\n"
"}")
        self.username_page_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_page_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_page_frame_2.setObjectName("username_page_frame_2")
        self.username_login_text_frame = QtWidgets.QFrame(self.username_page_frame_2)
        self.username_login_text_frame.setGeometry(QtCore.QRect(50, 320, 411, 81))
        self.username_login_text_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.username_login_text_frame.setStyleSheet("QFrame#username_login_text_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.username_login_text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_login_text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_login_text_frame.setObjectName("username_login_text_frame")
        self.username_login_text_box = QtWidgets.QLineEdit(self.username_login_text_frame)
        self.username_login_text_box.setGeometry(QtCore.QRect(10, 20, 391, 41))
        self.username_login_text_box.setStyleSheet("QLineEdit#username_login_text_box{\n"
"border-radius: 12px;\n"
"padding-left: 4px;\n"
"}")
        self.username_login_text_box.setText("")
        self.username_login_text_box.setMaxLength(15)
        self.username_login_text_box.setObjectName("username_login_text_box")
        self.login_server_frame = QtWidgets.QFrame(self.username_page_frame_2)
        self.login_server_frame.setGeometry(QtCore.QRect(170, 580, 181, 81))
        self.login_server_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.login_server_frame.setStyleSheet("QFrame#login_server_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.login_server_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_server_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_server_frame.setObjectName("login_server_frame")
        self.login_server_btn = QtWidgets.QPushButton(self.login_server_frame)
        self.login_server_btn.setGeometry(QtCore.QRect(20, 20, 141, 41))
        self.login_server_btn.setStyleSheet("QPushButton#login_server_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.login_server_btn.setObjectName("login_server_btn")
        self.back_login_server_frame = QtWidgets.QFrame(self.username_page_frame_2)
        self.back_login_server_frame.setGeometry(QtCore.QRect(30, 20, 131, 51))
        self.back_login_server_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.back_login_server_frame.setStyleSheet("QFrame#back_login_server_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.back_login_server_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back_login_server_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_login_server_frame.setObjectName("back_login_server_frame")
        self.back_login_server_btn = QtWidgets.QPushButton(self.back_login_server_frame)
        self.back_login_server_btn.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.back_login_server_btn.setStyleSheet("QPushButton#back_login_server_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.back_login_server_btn.setObjectName("back_login_server_btn")
        self.password_login_text_frame = QtWidgets.QFrame(self.username_page_frame_2)
        self.password_login_text_frame.setGeometry(QtCore.QRect(50, 420, 411, 81))
        self.password_login_text_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.password_login_text_frame.setStyleSheet("QFrame#password_login_text_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.password_login_text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_login_text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_login_text_frame.setObjectName("password_login_text_frame")
        self.password_login_text_box = QtWidgets.QLineEdit(self.password_login_text_frame)
        self.password_login_text_box.setGeometry(QtCore.QRect(10, 20, 391, 41))
        self.password_login_text_box.setStyleSheet("QLineEdit#password_login_text_box{\n"
"border-radius: 12px;\n"
"padding-left: 4px;\n"
"}")
        self.password_login_text_box.setText("")
        self.password_login_text_box.setMaxLength(15)
        self.password_login_text_box.setObjectName("password_login_text_box")
        self.username_login_label_frame = QtWidgets.QFrame(self.username_page_frame_2)
        self.username_login_label_frame.setGeometry(QtCore.QRect(60, 210, 391, 61))
        self.username_login_label_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.username_login_label_frame.setStyleSheet("QFrame#username_login_label_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.username_login_label_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_login_label_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_login_label_frame.setObjectName("username_login_label_frame")
        self.username_login_label = QtWidgets.QLabel(self.username_login_label_frame)
        self.username_login_label.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.username_login_label.setStyleSheet("QLabel#username_login_label{\n"
"border-radius: 10px;\n"
"}")
        self.username_login_label.setObjectName("username_login_label")
        self.stackedwidget.addWidget(self.login_page)
        self.username_page = QtWidgets.QWidget()
        self.username_page.setObjectName("username_page")
        self.username_page_frame = QtWidgets.QFrame(self.username_page)
        self.username_page_frame.setGeometry(QtCore.QRect(-1, -1, 501, 701))
        self.username_page_frame.setStyleSheet("QFrame#username_page_frame{\n"
"background-color: rgb(179, 179, 179);\n"
"}")
        self.username_page_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_page_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_page_frame.setObjectName("username_page_frame")
        self.username_text_frame = QtWidgets.QFrame(self.username_page_frame)
        self.username_text_frame.setGeometry(QtCore.QRect(40, 370, 411, 81))
        self.username_text_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.username_text_frame.setStyleSheet("QFrame#username_text_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.username_text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_text_frame.setObjectName("username_text_frame")
        self.username_text_box = QtWidgets.QLineEdit(self.username_text_frame)
        self.username_text_box.setGeometry(QtCore.QRect(10, 20, 391, 41))
        self.username_text_box.setStyleSheet("QLineEdit#username_text_box{\n"
"border-radius: 12px;\n"
"padding-left: 4px;\n"
"}")
        self.username_text_box.setText("")
        self.username_text_box.setMaxLength(15)
        self.username_text_box.setObjectName("username_text_box")
        self.username_label_frame = QtWidgets.QFrame(self.username_page_frame)
        self.username_label_frame.setGeometry(QtCore.QRect(60, 90, 391, 61))
        self.username_label_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.username_label_frame.setStyleSheet("QFrame#username_label_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.username_label_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_label_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_label_frame.setObjectName("username_label_frame")
        self.username_label = QtWidgets.QLabel(self.username_label_frame)
        self.username_label.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.username_label.setStyleSheet("QLabel#username_label{\n"
"border-radius: 10px;\n"
"}")
        self.username_label.setObjectName("username_label")
        self.join_server_frame = QtWidgets.QFrame(self.username_page_frame)
        self.join_server_frame.setGeometry(QtCore.QRect(140, 600, 181, 81))
        self.join_server_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.join_server_frame.setStyleSheet("QFrame#join_server_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.join_server_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.join_server_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.join_server_frame.setObjectName("join_server_frame")
        self.join_server_btn = QtWidgets.QPushButton(self.join_server_frame)
        self.join_server_btn.setGeometry(QtCore.QRect(20, 20, 141, 41))
        self.join_server_btn.setStyleSheet("QPushButton#join_server_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.join_server_btn.setObjectName("join_server_btn")
        self.back_join_server_frame = QtWidgets.QFrame(self.username_page_frame)
        self.back_join_server_frame.setGeometry(QtCore.QRect(30, 20, 131, 51))
        self.back_join_server_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.back_join_server_frame.setStyleSheet("QFrame#back_join_server_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.back_join_server_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back_join_server_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_join_server_frame.setObjectName("back_join_server_frame")
        self.back_join_server_btn = QtWidgets.QPushButton(self.back_join_server_frame)
        self.back_join_server_btn.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.back_join_server_btn.setStyleSheet("QPushButton#back_join_server_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.back_join_server_btn.setObjectName("back_join_server_btn")
        self.intro_frame = QtWidgets.QFrame(self.username_page_frame)
        self.intro_frame.setGeometry(QtCore.QRect(150, 190, 201, 141))
        self.intro_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.intro_frame.setStyleSheet("QFrame#intro_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.intro_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.intro_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.intro_frame.setObjectName("intro_frame")
        self.intro_text = QtWidgets.QPlainTextEdit(self.intro_frame)
        self.intro_text.setGeometry(QtCore.QRect(10, 10, 181, 121))
        self.intro_text.setObjectName("intro_text")
        self.password_text_frame = QtWidgets.QFrame(self.username_page_frame)
        self.password_text_frame.setGeometry(QtCore.QRect(40, 470, 411, 81))
        self.password_text_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.password_text_frame.setStyleSheet("QFrame#password_text_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.password_text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_text_frame.setObjectName("password_text_frame")
        self.password_text_box = QtWidgets.QLineEdit(self.password_text_frame)
        self.password_text_box.setGeometry(QtCore.QRect(10, 20, 391, 41))
        self.password_text_box.setStyleSheet("QLineEdit#password_text_box{\n"
"border-radius: 12px;\n"
"padding-left: 4px;\n"
"}")
        self.password_text_box.setText("")
        self.password_text_box.setMaxLength(15)
        self.password_text_box.setObjectName("password_text_box")
        self.stackedwidget.addWidget(self.username_page)
        self.groups_page = QtWidgets.QWidget()
        self.groups_page.setObjectName("groups_page")
        self.group_chats_frame = QtWidgets.QFrame(self.groups_page)
        self.group_chats_frame.setGeometry(QtCore.QRect(-1, -1, 511, 701))
        self.group_chats_frame.setStyleSheet("QFrame#group_chats_frame{\n"
"background-color: rgb(179, 179, 179);\n"
"}")
        self.group_chats_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_chats_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_chats_frame.setObjectName("group_chats_frame")
        self.groups_bottom_frame = QtWidgets.QFrame(self.group_chats_frame)
        self.groups_bottom_frame.setGeometry(QtCore.QRect(-1, 0, 511, 80))
        self.groups_bottom_frame.setStyleSheet("QFrame#groups_bottom_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"}")
        self.groups_bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groups_bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groups_bottom_frame.setObjectName("groups_bottom_frame")
        self.leave_server = QtWidgets.QPushButton(self.groups_bottom_frame)
        self.leave_server.setGeometry(QtCore.QRect(20, 20, 91, 51))
        self.leave_server.setStyleSheet("QPushButton#leave_server{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.leave_server.setObjectName("leave_server")
        self.public_chat_btn = QtWidgets.QPushButton(self.groups_bottom_frame)
        self.public_chat_btn.setGeometry(QtCore.QRect(390, 20, 91, 51))
        self.public_chat_btn.setStyleSheet("QPushButton#public_chat_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.public_chat_btn.setObjectName("public_chat_btn")
        self.create_group_btn = QtWidgets.QPushButton(self.groups_bottom_frame)
        self.create_group_btn.setGeometry(QtCore.QRect(280, 20, 91, 51))
        self.create_group_btn.setStyleSheet("QPushButton#create_group_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.create_group_btn.setObjectName("create_group_btn")
        self.scrollArea = QtWidgets.QScrollArea(self.group_chats_frame)
        self.scrollArea.setGeometry(QtCore.QRect(40, 380, 431, 301))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 429, 299))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.joinable_groups_frame = QtWidgets.QFrame(self.group_chats_frame)
        self.joinable_groups_frame.setGeometry(QtCore.QRect(140, 320, 241, 41))
        self.joinable_groups_frame.setStyleSheet("QFrame#joinable_groups_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 12px;\n"
"}")
        self.joinable_groups_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joinable_groups_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joinable_groups_frame.setObjectName("joinable_groups_frame")
        self.joinable_groups_label = QtWidgets.QFrame(self.joinable_groups_frame)
        self.joinable_groups_label.setGeometry(QtCore.QRect(20, 10, 201, 21))
        self.joinable_groups_label.setStyleSheet("border-radius: 12px;")
        self.joinable_groups_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joinable_groups_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joinable_groups_label.setObjectName("joinable_groups_label")
        self.label_3 = QtWidgets.QLabel(self.joinable_groups_label)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 201, 20))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.stackedwidget.addWidget(self.groups_page)
        self.group_creator_page = QtWidgets.QWidget()
        self.group_creator_page.setObjectName("group_creator_page")
        self.server_creation_frame = QtWidgets.QFrame(self.group_creator_page)
        self.server_creation_frame.setGeometry(QtCore.QRect(-10, 0, 511, 701))
        self.server_creation_frame.setStyleSheet("QFrame#server_creation_frame{\n"
"background-color: rgb(179, 179, 179);\n"
"}")
        self.server_creation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.server_creation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.server_creation_frame.setObjectName("server_creation_frame")
        self.add_members_scrollwheel = QtWidgets.QScrollArea(self.server_creation_frame)
        self.add_members_scrollwheel.setGeometry(QtCore.QRect(40, 410, 201, 271))
        self.add_members_scrollwheel.setStyleSheet("")
        self.add_members_scrollwheel.setWidgetResizable(True)
        self.add_members_scrollwheel.setObjectName("add_members_scrollwheel")
        
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 199, 269))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.add_members_scrollwheel.setWidget(self.scrollAreaWidgetContents_3)
        self.groups_top_frame = QtWidgets.QFrame(self.server_creation_frame)
        self.groups_top_frame.setGeometry(QtCore.QRect(0, -1, 511, 101))
        self.groups_top_frame.setStyleSheet("QFrame#groups_top_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"}")
        self.groups_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groups_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groups_top_frame.setObjectName("groups_top_frame")
        self.leave_group_creation = QtWidgets.QPushButton(self.groups_top_frame)
        self.leave_group_creation.setGeometry(QtCore.QRect(30, 30, 121, 61))
        self.leave_group_creation.setStyleSheet("QPushButton#leave_group_creation{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.leave_group_creation.setObjectName("leave_group_creation")
        self.create_group = QtWidgets.QPushButton(self.groups_top_frame)
        self.create_group.setGeometry(QtCore.QRect(370, 30, 121, 61))
        self.create_group.setStyleSheet("QPushButton#create_group{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.create_group.setObjectName("create_group")
        self.server_text_frame = QtWidgets.QFrame(self.server_creation_frame)
        self.server_text_frame.setGeometry(QtCore.QRect(60, 230, 411, 81))
        self.server_text_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.server_text_frame.setStyleSheet("QFrame#server_text_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.server_text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.server_text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.server_text_frame.setObjectName("server_text_frame")
        self.server_text_box = QtWidgets.QLineEdit(self.server_text_frame)
        self.server_text_box.setGeometry(QtCore.QRect(10, 20, 391, 41))
        self.server_text_box.setStyleSheet("QLineEdit#server_text_box{\n"
"border-radius: 12px;\n"
"padding-left: 4px;\n"
"}")
        self.server_text_box.setText("")
        self.server_text_box.setMaxLength(15)
        self.server_text_box.setObjectName("server_text_box")
        self.server_creation_text_frame = QtWidgets.QFrame(self.server_creation_frame)
        self.server_creation_text_frame.setGeometry(QtCore.QRect(130, 160, 291, 51))
        self.server_creation_text_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.server_creation_text_frame.setStyleSheet("QFrame#server_creation_text_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.server_creation_text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.server_creation_text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.server_creation_text_frame.setObjectName("server_creation_text_frame")
        self.server_creation_label = QtWidgets.QLabel(self.server_creation_text_frame)
        self.server_creation_label.setGeometry(QtCore.QRect(20, 10, 251, 31))
        self.server_creation_label.setStyleSheet("padding-left: 2px;")
        self.server_creation_label.setObjectName("server_creation_label")
        self.availible_members_btn = QtWidgets.QFrame(self.server_creation_frame)
        self.availible_members_btn.setGeometry(QtCore.QRect(120, 340, 291, 51))
        self.availible_members_btn.setMaximumSize(QtCore.QSize(501, 16777215))
        self.availible_members_btn.setStyleSheet("QFrame#availible_members_btn{\n"
"background-color:rgb(84, 122, 184);\n"
"border-radius: 14px;\n"
"}")
        self.availible_members_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.availible_members_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.availible_members_btn.setObjectName("availible_members_btn")
        self.availible_members = QtWidgets.QLabel(self.availible_members_btn)
        self.availible_members.setGeometry(QtCore.QRect(10, 10, 271, 31))
        self.availible_members.setStyleSheet("padding-left: 2px;")
        self.availible_members.setObjectName("availible_members")
        self.added_members = QtWidgets.QTextBrowser(self.server_creation_frame)
        self.added_members.setGeometry(QtCore.QRect(285, 411, 201, 271))
        self.added_members.setObjectName("added_members")
        self.stackedwidget.addWidget(self.group_creator_page)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.chat_bottom_frame = QtWidgets.QFrame(self.main_page)
        self.chat_bottom_frame.setGeometry(QtCore.QRect(0, 620, 500, 81))
        self.chat_bottom_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.chat_bottom_frame.setStyleSheet("QFrame#chat_bottom_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"}")
        self.chat_bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_bottom_frame.setObjectName("chat_bottom_frame")
        self.message_text_box = QtWidgets.QLineEdit(self.chat_bottom_frame)
        self.message_text_box.setGeometry(QtCore.QRect(10, 20, 371, 41))
        self.message_text_box.setStyleSheet("QLineEdit#message_text_box{\n"
"border-radius: 12px;\n"
"padding-left: 4px;\n"
"}")
        self.message_text_box.setText("")
        self.message_text_box.setMaxLength(400)
        self.message_text_box.setObjectName("message_text_box")
        self.message_send_btn = QtWidgets.QPushButton(self.chat_bottom_frame)
        self.message_send_btn.setGeometry(QtCore.QRect(400, 20, 81, 41))
        self.message_send_btn.setStyleSheet("QPushButton#message_send_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.message_send_btn.setObjectName("message_send_btn")
        self.chat_text_browser = QtWidgets.QTextBrowser(self.main_page)
        self.chat_text_browser.setGeometry(QtCore.QRect(0, 80, 501, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_text_browser.sizePolicy().hasHeightForWidth())
        self.chat_text_browser.setSizePolicy(sizePolicy)
        self.chat_text_browser.setStyleSheet("QTextBrowser#chat_text_browser{\n"
"background-color: rgb(179, 179, 179);\n"
"padding-left: 4px;\n"
"padding-top: 5px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.chat_text_browser.setObjectName("chat_text_browser")
        self.chat_top_frame = QtWidgets.QFrame(self.main_page)
        self.chat_top_frame.setGeometry(QtCore.QRect(0, 0, 500, 81))
        self.chat_top_frame.setMaximumSize(QtCore.QSize(501, 81))
        self.chat_top_frame.setStyleSheet("QFrame#chat_top_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"}")
        self.chat_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_top_frame.setObjectName("chat_top_frame")
        self.back_chat_btn = QtWidgets.QPushButton(self.chat_top_frame)
        self.back_chat_btn.setGeometry(QtCore.QRect(20, 20, 91, 51))
        self.back_chat_btn.setStyleSheet("QPushButton#leave_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.back_chat_btn.setObjectName("back_chat_btn")
        self.chat_members_btn = QtWidgets.QPushButton(self.chat_top_frame)
        self.chat_members_btn.setGeometry(QtCore.QRect(390, 20, 91, 51))
        self.chat_members_btn.setStyleSheet("QPushButton#chat_members_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.chat_members_btn.setObjectName("chat_members_btn")
        self.members_scrollArea = QtWidgets.QScrollArea(self.main_page)
        self.members_scrollArea.setGeometry(QtCore.QRect(330, 220, 171, 281))
        self.members_scrollArea.setWidgetResizable(True)
        self.members_scrollArea.setObjectName("members_scrollArea")
        self.members_scrollArea.hide()
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 169, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.members_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.chat_text_browser.raise_()
        self.chat_bottom_frame.raise_()
        self.chat_top_frame.raise_()
        self.members_scrollArea.raise_()
        self.stackedwidget.addWidget(self.main_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.profile_frame = QtWidgets.QFrame(self.profile_page)
        self.profile_frame.setGeometry(QtCore.QRect(-1, -1, 501, 701))
        self.profile_frame.setStyleSheet("QFrame#profile_frame{\n"
"background-color: rgb(179, 179, 179);\n"
"}")
        self.profile_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_frame.setObjectName("profile_frame")
        self.profile_details_frame = QtWidgets.QFrame(self.profile_frame)
        self.profile_details_frame.setGeometry(QtCore.QRect(0, 380, 500, 321))
        self.profile_details_frame.setMaximumSize(QtCore.QSize(501, 16777215))
        self.profile_details_frame.setStyleSheet("QFrame#profile_details_frame{\n"
"background-color:rgb(84, 122, 184);\n"
"}")
        self.profile_details_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile_details_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_details_frame.setObjectName("profile_details_frame")
        self.leave_profiles_btn = QtWidgets.QPushButton(self.profile_details_frame)
        self.leave_profiles_btn.setGeometry(QtCore.QRect(170, 70, 141, 41))
        self.leave_profiles_btn.setStyleSheet("QPushButton#leave_profiles_btn{\n"
"border-radius: 12px;\n"
"}\n"
"")
        self.leave_profiles_btn.setObjectName("leave_profiles_btn")
        self.username_profile = QtWidgets.QLabel(self.profile_frame)
        self.username_profile.setGeometry(QtCore.QRect(140, 150, 231, 31))
        self.username_profile.setText("")
        self.username_profile.setObjectName("username_profile")
        self.intro_profile_desc = QtWidgets.QLabel(self.profile_frame)
        self.intro_profile_desc.setGeometry(QtCore.QRect(80, 270, 361, 71))
        self.intro_profile_desc.setStyleSheet("QLabel#intro_profile_desc{\n"
"border-radius: 12px;\n"
"}")
        self.intro_profile_desc.setText("")
        self.intro_profile_desc.setObjectName("intro_profile_desc")
        self.stackedwidget.addWidget(self.profile_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedwidget.setCurrentWidget(self.join_server_page)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ip_text_box.setPlaceholderText(_translate("MainWindow", "Type here"))
        self.ip_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Please enter your the servers public ip address!</span></p></body></html>"))
        self.signup_btn.setText(_translate("MainWindow", "sign up"))
        self.login_btn.setText(_translate("MainWindow", "login"))
        self.username_login_text_box.setPlaceholderText(_translate("MainWindow", "username"))
        self.login_server_btn.setText(_translate("MainWindow", "Enter chat"))
        self.back_login_server_btn.setText(_translate("MainWindow", "back to host page"))
        self.password_login_text_box.setPlaceholderText(_translate("MainWindow", "password"))
        self.username_login_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Create your profile!</p></body></html>"))
        self.username_text_box.setPlaceholderText(_translate("MainWindow", "username"))
        self.username_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Create your profile!</p></body></html>"))
        self.join_server_btn.setText(_translate("MainWindow", "Enter chat"))
        self.back_join_server_btn.setText(_translate("MainWindow", "back to host page"))
        self.intro_text.setPlaceholderText(_translate("MainWindow", "introduction"))
        self.password_text_box.setPlaceholderText(_translate("MainWindow", "password"))
        self.leave_server.setText(_translate("MainWindow", "leave Server"))
        self.public_chat_btn.setText(_translate("MainWindow", "public chat"))
        self.create_group_btn.setText(_translate("MainWindow", "create Group"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">joinable groups</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.leave_group_creation.setText(_translate("MainWindow", "leave group creator"))
        self.create_group.setText(_translate("MainWindow", "create group"))
        self.server_text_box.setPlaceholderText(_translate("MainWindow", "Group Name"))
        self.server_creation_label.setText(_translate("MainWindow", "Add server members and add a group name!"))
        self.availible_members.setText(_translate("MainWindow", "click name to add to server and click again to remove"))
        self.message_text_box.setPlaceholderText(_translate("MainWindow", "Type here"))
        self.message_send_btn.setText(_translate("MainWindow", "Send"))
        self.back_chat_btn.setText(_translate("MainWindow", "Leave chat"))
        self.chat_members_btn.setText(_translate("MainWindow", "members"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.leave_profiles_btn.setText(_translate("MainWindow", "back to host page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
